---
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  setup:
    name: Setup environment
    if: |
      github.event.head_commit.message != 'Initial commit' &&
      !startsWith(github.event.head_commit.message, 'docs: update CHANGELOG.md')
    uses: ./.github/workflows/wf-setup.yml

  release:
    name: Tag and release
    needs: setup
    if: needs.setup.outputs.tag_version != ''
    uses: ./.github/workflows/wf-release.yml
    with:
      tag_version: ${{ needs.setup.outputs.tag_version }}
      bump_type: ${{ needs.setup.outputs.bump_type }}
      github_repository: ${{ github.repository }}
      changelog_entries: ${{ needs.setup.outputs.changelog_entries }}
