name: Lint

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  lint:
    name: Lint workflows and actions
    uses: ./.github/workflows/wf-lint.yml
    with:
      yamllint_paths: |
        .github/workflows/
        actions/
