name: Release (Reusable)

on:
  workflow_call:
    inputs:
      tag_version:
        required: true
        type: string
      bump_type:
        required: true
        type: string
      github_repository:
        required: true
        type: string
      changelog_entries:
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    environment: production
    if: inputs.tag_version != ''
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Update CHANGELOG.md
        run: |
          TEMP=$(mktemp)
          echo "# Changelog" > $TEMP
          echo "" >> $TEMP
          echo "## [${{ inputs.tag_version }}](https://github.com/${{ inputs.github_repository }}/releases/tag/${{ inputs.tag_version }}) ($(date +'%Y-%m-%d'))" >> $TEMP
          echo "" >> $TEMP
          echo "${{ inputs.changelog_entries }}" >> $TEMP
          echo "" >> $TEMP
          [ -f CHANGELOG.md ] && sed '/^# Changelog$/d' CHANGELOG.md >> $TEMP
          mv $TEMP CHANGELOG.md

      - name: Commit and push CHANGELOG
        uses: qoomon/actions--create-commit@v1.2.3
        with:
          message: "docs: update CHANGELOG.md for ${{ inputs.tag_version }}"
          skip-empty: true

      - name: Push
        run: git push

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2.6.1
        with:
          tag_name: ${{ inputs.tag_version }}
          name: "Release ${{ inputs.tag_version }}"
          prerelease: false
          draft: false
          generate_release_notes: true
          body: |
            **Bump type:** `${{ inputs.bump_type }}`

            <details>
              <summary>Changelog</summary>

              ${{ inputs.changelog_entries }}
            </details>

      - name: Release summary
        run: |
          echo "## Release summary" >> $GITHUB_STEP_SUMMARY
          echo "| Field | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Release | [${{ inputs.tag_version }}](https://github.com/${{ inputs.github_repository }}/releases/tag/${{ inputs.tag_version }}) |" >> $GITHUB_STEP_SUMMARY
          echo "| Bump type | \`${{ inputs.bump_type }}\` |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Changelog" >> $GITHUB_STEP_SUMMARY
          echo "${{ inputs.changelog_entries }}" >> $GITHUB_STEP_SUMMARY
